application: pixelite-web
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /cache\.manifest
  static_files: cache.manifest
  mime_type: text/cache-manifest
  upload: cache\.manifest


- url: /fonts
  static_dir: fonts


- url: /img
  static_dir: img


- url: /js
  static_dir: js

- url: /start
  static_files: app.txt
  mime_type: text/html
  upload: app\.txt


- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"